Update build_and_release_signed_apk.yml

diff --git a/.github/workflows/build_and_release_signed_apk.yml b/.github/workflows/build_and_release_signed_apk.yml
--- a/.github/workflows/build_and_release_signed_apk.yml
+++ b/.github/workflows/build_and_release_signed_apk.yml
@@ -23,13 +23,13 @@ jobs:
 
       - name: Decode Keystore
         run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d -w 0 > keystore.jks
-        
+
       - name: Grant execute permission for Gradlew
         run: chmod +x ./gradlew
 
       - name: Build Signed APK
         run: |
-          ./gradlew assembleRelease \
+          ./gradlew assembleRelease --stacktrace \
             -Pandroid.injected.signing.store.file=$(pwd)/keystore.jks \
             -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
             -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
@@ -45,7 +45,14 @@ jobs:
           APK_FILE="app/build/outputs/apk/release/app-release.apk"
           NEW_APK_NAME="Expense Tracker v${VERSION_STRING}.apk"
           mv "$APK_FILE" "$APK_FILE/../../$NEW_APK_NAME"
-      
+
+      - name: Check if APK exists
+        run: |
+          if [ ! -f "${{ github.workspace }}/Expense Tracker v${{ env.VERSION_NAME }}.apk" ]; then
+            echo "APK file not found!"
+            exit 1
+          fi
+
       - name: Create GitHub Release
         uses: softprops/action-gh-release@v1
         with:
